name: YAML validation

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  yaml-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v1
        with:
          ## File(s) or Directory, separate by space if multiple files or folder are specified
          file_or_dir: model/
          ## Custom configuration (as YAML source)
          config_data: "{extends: default, rules: {line-length: disable}}"
          ## Format for parsing output [parsable,standard,colored,auto]
          # format: # optional, default is colored
          ## Return non-zero exit code on warnings as well as errors
          # strict: # optional, default is false

      - name: Import with cobrapy
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/metabolicatlas/memote-docker:0.13
          options: -v ${{ github.workspace }}:/opt
          shell: bash
          run: |
            cd /opt
            python -c "import cobra ; cobra.io.load_yaml_model('model/yeast-GEM.yml')"
